### PR TITLE
Added fuzzaldrin algorithm (ported to C++) as a possible choice

### PR DESCRIPTION
**Pull request by mauricioszabo**
New option of API:

```js
matcher.match('tiatd', {algorithm: 'fuzzaldrin'})
```

### CODE REVIEW

**Comment by confused-Techie** [comment]
These changes look super solid, and love to see new tests added for it.

Although does make me slightly nervous to not have any testing strategy on this package to confirm that the old and new tests are still happy on every supported platform.

So I'll add a light approval missing that, as I'm assuming tests are passing for you locally, but would be much more happy to provide a proper approval if we maybe added an action to test on every supported platform here, like we do other tests

**Comment by mauricioszabo** [comment]
Wait, you're right: we don't have tests added to this repo!

I'll add them - I ran the tests locally, and they all passed indeed.

**Comment by mauricioszabo** [comment]
Done, testing is activated - and they indeed pass!

(That was easy - honestly, one of the first times I got it working in under than 10 minutes!)

**Comment by confused-Techie** [comment]
@mauricioszabo Thanks a ton for addressing my feedback, love to see it!

**Pull request merged**
